name: CD

on:
  push:
    branches: [ main ]

concurrency:
  group: "cd"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
      
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v3
      - uses: actions/configure-pages@v5
      - uses: gradle/actions/setup-gradle@v3
      - name: Build with Gradle
        run: ./gradlew build
      - uses: actions/upload-pages-artifact@v3
        with:
          path: build/distributions
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
